export const AUDIT_ACTIONS = {
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGOUT: "LOGOUT",
  USER_CREATED: "USER_CREATED",
  ROLE_CHANGED: "ROLE_CHANGED",
  PARTICIPANT_REGISTERED: "PARTICIPANT_REGISTERED",
  PROGRAM_CREATED: "PROGRAM_CREATED",
  PAYMENT_INITIATED: "PAYMENT_INITIATED",
  PAYMENT_COMPLETED: "PAYMENT_COMPLETED",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  PAYMENT_REFUNDED: "PAYMENT_REFUNDED",
  SEAT_UPGRADE_COMPLETED: "SEAT_UPGRADE_COMPLETED",
  REPORT_EXPORTED: "REPORT_EXPORTED",
  SETTINGS_UPDATED: "SETTINGS_UPDATED",
  AI_CHAT_USED: "AI_CHAT_USED",
  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  TWO_FACTOR_ENABLED: "TWO_FACTOR_ENABLED",
  TWO_FACTOR_DISABLED: "TWO_FACTOR_DISABLED",
  CERTIFICATE_ISSUED: "CERTIFICATE_ISSUED",
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];

export const METRIC_NAMES = {
  REGISTRATION_RATE: "RegistrationRate",
  PAYMENT_FAILURES: "PaymentFailures",
  AI_USAGE: "AiUsage",
  SEAT_UTILIZATION: "SeatUtilization",
} as const;

export type MetricName = (typeof METRIC_NAMES)[keyof typeof METRIC_NAMES];
