import { readFileSync, existsSync } from "fs";
import type { PrismaClient } from "@prisma/client";
import type { ParsedUnit } from "../src/lib/training/idea-dev-parser";

/**
 * Loads the Idea Development training units from the data generated by
 * scripts/import-idea-dev-questions.ts. Idempotent: units and questions are
 * matched by order and updated in place, so existing attempts keep pointing
 * at the same exams and questions.
 */

/** Same key as src/lib/training/units-service.ts (not imported: that module opens its own DB client). */
export const IDEA_DEV_TRAINING_KEY = "idea_development_sim";
const DATA_FILE = "prisma/seed-data/idea-development.json";

/** Unit order -> program-calendar activity (see src/lib/programs/schedule.ts). */
const UNIT_ACTIVITIES = [
  "CREATIVE_THINKING",
  "MULTIPLE_PERSPECTIVES",
  "PROBLEM_DISCOVERY",
  "UNDERSTANDING_USERS",
  "INSIGHT_OPPORTUNITY",
  "IDEA_GENERATION",
  "IDEA_EVALUATION",
  "VALUE_PROPOSITION",
] as const;

const UNIT_POINTS = 100;
const PASSING_THRESHOLD = 60;

type Messages = { programSchedule: { activities: Record<string, string> }; tenant: { simulationTypes: Record<string, string> } };
const messages = (locale: string) => JSON.parse(readFileSync(`messages/${locale}.json`, "utf8")) as Messages;

export async function seedIdeaDevelopmentTraining(prisma: PrismaClient) {
  if (!existsSync(DATA_FILE)) {
    console.log(`Skipping training units: ${DATA_FILE} not found (run scripts/import-idea-dev-questions.ts).`);
    return;
  }
  const { units } = JSON.parse(readFileSync(DATA_FILE, "utf8")) as { units: ParsedUnit[] };
  const [tr, en, az] = ["tr", "en", "az"].map(messages);
  const title = (m: Messages, activity: string) => m.programSchedule.activities[activity];

  const training = await prisma.training.upsert({
    where: { key: IDEA_DEV_TRAINING_KEY },
    update: {},
    create: {
      key: IDEA_DEV_TRAINING_KEY,
      titleTr: tr.tenant.simulationTypes.idea_development,
      titleEn: en.tenant.simulationTypes.idea_development,
      titleAz: az.tenant.simulationTypes.idea_development,
      category: "idea_development",
    },
  });

  for (const unit of units) {
    const activity = UNIT_ACTIVITIES[unit.order - 1];
    const titles = { titleTr: title(tr, activity), titleEn: title(en, activity), titleAz: title(az, activity) };
    const lessonData = {
      ...titles,
      title: titles.titleTr,
      content: unit.project.scenario,
      activity,
      projectBrief: JSON.stringify(unit.project),
      points: UNIT_POINTS,
      estimatedMinutes: 30,
      // Videos are added later; the unit screen shows a placeholder until then.
    };
    const existingLesson = await prisma.lesson.findFirst({ where: { trainingId: training.id, order: unit.order } });
    const lesson = existingLesson
      ? await prisma.lesson.update({ where: { id: existingLesson.id }, data: lessonData })
      : await prisma.lesson.create({ data: { ...lessonData, trainingId: training.id, order: unit.order } });

    const exam =
      (await prisma.exam.findFirst({ where: { lessonId: lesson.id } })) ??
      (await prisma.exam.create({
        data: { trainingId: training.id, lessonId: lesson.id, ...titles, title: titles.titleTr, passingThreshold: PASSING_THRESHOLD },
      }));

    const existingQuestions = await prisma.question.findMany({ where: { examId: exam.id }, orderBy: { order: "asc" } });
    for (const [i, q] of unit.questions.entries()) {
      const data = {
        questionText: q.text,
        optionA: q.options.A,
        optionB: q.options.B,
        optionC: q.options.C,
        optionD: q.options.D,
        correctOption: q.correct,
        explanation: "",
        order: i + 1,
      };
      const match = existingQuestions.find((e) => e.order === i + 1);
      if (match) await prisma.question.update({ where: { id: match.id }, data });
      else await prisma.question.create({ data: { ...data, examId: exam.id } });
    }
    const extra = existingQuestions.filter((e) => e.order > unit.questions.length).map((e) => e.id);
    if (extra.length > 0) await prisma.question.deleteMany({ where: { id: { in: extra } } });
  }
  console.log(`Training units: ${units.length} (${IDEA_DEV_TRAINING_KEY})`);
}
